require("features.ui.colorscheme.config")
require("features.ui.file_tree.config")
require("features.ui.statusbar.config")
require("features.ui.whichkey.config")
require("features.ui.git.config")
require("features.ui.tabs.config")
require("features.ui.md.config")
require("features.ui.cmdline_and_notifications.config")

require("features.programming.syntax_highlighting.config")
require("features.programming.completion.config")
require("features.programming.lsp.config")
