require("features.ui.colorscheme.config")
require("features.ui.file_tree.config")
require("features.ui.statusbar.config")
require("features.ui.dashboard.config")
require("features.ui.whichkey.config")
require("features.ui.git.config")
require("features.ui.tabs.config")

require("features.language_features.syntax_highlighting.config")
require("features.language_features.completion.config")
require("features.language_features.lsp.config")
require("features.language_features.formating.config")
